### PR TITLE
Windows Support for Library

### PR DESCRIPTION
**Pull request by aboss123**
There was no windows support before and there is windows support now. I closed the other pull request because it did not have proper comments. This one shows what each flag ends up doing. To write this code  I used Microsoft's Documentation: https://docs.microsoft.com/en-us/windows/console/setconsolemode. If you want to do anything more  on Windows I suggest you read their flags and their functions. If you want to set color the old way on console you can use `SetConsoleTextAttribute `but I suggest you use this instead.

### CODE REVIEW

**Comment by euppal** [comment]
Thanks! I got that windows code from a friend who knew windows. Does this build?

**Comment by euppal** [comment]
In one of your commits it seems that the tabs were changed from 4-space to 2-space. I assume it was just your editor doing this automatically and not your fault. While this isn't a necessary fix, it would be nice to have consistent code style, so if you could make that quick change then it looks good!

**Comment by aboss123** [comment]
Ok Thanks Got it. I will make that code change to have 4 space tab. I used CMake to build it on windows and make on my linux machine and both work well. So I'd assume it also would work on MacOS too. I'll make the change and put it here.

**Comment by aboss123** [comment]
I fixed the idents now (hopefully) it all looks good enough to merge :)

**Comment by aboss123** [comment]
Oh it looks like in the original that your macros also have indents let me fix that.

**Comment by aboss123** [comment]
Should be good now let me know if anything else needs to be changed.

**Comment by euppal** [comment]
Nope, merging now!

**Pull request merged**
